### ISSUE TITLE
dtlu-project-maker -p non_existent causes exception

### ISSUE THREAD

**Issue by jirislaby** [Linhos13/dtlu#3]
xy doesn't exist yet and running:
```
$ dtlu-project-maker -m Makefile -p xy
Traceback (most recent call last):
  File "/usr/bin/dtlu-project-maker", line 233, in <module>
    main(sys.argv[1:])
  File "/usr/bin/dtlu-project-maker", line 224, in main
    make_project(outputDirectory, makefile)
  File "/usr/bin/dtlu-project-maker", line 192, in make_project
    proj = open(os.path.join(project_dir, ".project"),"w")
IOError: [Errno 2] No such file or directory: '/tmp/busybox-1.25.1/xy/.project'
```
It should handle the error properly.

**Comment by Linhos13** [comment]
Added check if project dir exists and if is a directory.
