### ISSUE TITLE
Command '['dtlu-indexer', '/tmp/tmp.S6bpvgK9bJ']' returned non-zero exit status 2

### ISSUE THREAD

**Issue by jirislaby** [Linhos13/dtlu#6]
Is this what you ere talking about the generated tmp files?
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/trace.py", line 819, in <module>
    main()
  File "/usr/lib64/python2.7/trace.py", line 807, in main
    t.runctx(code, globs, globs)
  File "/usr/lib64/python2.7/trace.py", line 513, in runctx
    exec cmd in globals, locals
  File "/usr/bin/dtlu-project-maker", line 233, in <module>
    main(sys.argv[1:])
  File "/usr/bin/dtlu-project-maker", line 224, in main
    make_project(outputDirectory, makefile)
  File "/usr/bin/dtlu-project-maker", line 196, in make_project
    remake_project(project_dir)
  File "/usr/bin/dtlu-project-maker", line 187, in remake_project
    index_functions(project_dir)
  File "/usr/bin/dtlu-project-maker", line 151, in index_functions
    output = subprocess.check_output([indexer, f])
  File "/usr/lib64/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['dtlu-indexer', '/tmp/tmp.S6bpvgK9bJ']' returned non-zero exit status 2
```

In any way, better error should be printed out.

**Comment by Linhos13** [comment]
It crashed in compile part in my case. Error printing added. If you want skip tmp files indexing erase them from .files file. Then run "dtlu-project-maker -p project_dir -i" (add only indexing files specified in .files file.
